/*
Svix API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StreamEventTypeIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamEventTypeIn{}

// StreamEventTypeIn struct for StreamEventTypeIn
type StreamEventTypeIn struct {
	Description *string `json:"description,omitempty"`
	// The event type's name
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9\\\\-_.]+$"`
}

type _StreamEventTypeIn StreamEventTypeIn

// NewStreamEventTypeIn instantiates a new StreamEventTypeIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamEventTypeIn(name string) *StreamEventTypeIn {
	this := StreamEventTypeIn{}
	this.Name = name
	return &this
}

// NewStreamEventTypeInWithDefaults instantiates a new StreamEventTypeIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamEventTypeInWithDefaults() *StreamEventTypeIn {
	this := StreamEventTypeIn{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StreamEventTypeIn) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamEventTypeIn) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StreamEventTypeIn) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StreamEventTypeIn) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *StreamEventTypeIn) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StreamEventTypeIn) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StreamEventTypeIn) SetName(v string) {
	o.Name = v
}

func (o StreamEventTypeIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamEventTypeIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *StreamEventTypeIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamEventTypeIn := _StreamEventTypeIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamEventTypeIn)

	if err != nil {
		return err
	}

	*o = StreamEventTypeIn(varStreamEventTypeIn)

	return err
}

type NullableStreamEventTypeIn struct {
	value *StreamEventTypeIn
	isSet bool
}

func (v NullableStreamEventTypeIn) Get() *StreamEventTypeIn {
	return v.value
}

func (v *NullableStreamEventTypeIn) Set(val *StreamEventTypeIn) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamEventTypeIn) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamEventTypeIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamEventTypeIn(val *StreamEventTypeIn) *NullableStreamEventTypeIn {
	return &NullableStreamEventTypeIn{value: val, isSet: true}
}

func (v NullableStreamEventTypeIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamEventTypeIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


