/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EndpointHeadersIn struct for EndpointHeadersIn
type EndpointHeadersIn struct {
	Headers map[string]string `json:"headers"`
}

// NewEndpointHeadersIn instantiates a new EndpointHeadersIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointHeadersIn(headers map[string]string) *EndpointHeadersIn {
	this := EndpointHeadersIn{}
	this.Headers = headers
	return &this
}

// NewEndpointHeadersInWithDefaults instantiates a new EndpointHeadersIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointHeadersInWithDefaults() *EndpointHeadersIn {
	this := EndpointHeadersIn{}
	return &this
}

// GetHeaders returns the Headers field value
func (o *EndpointHeadersIn) GetHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *EndpointHeadersIn) GetHeadersOk() (*map[string]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Headers, true
}

// SetHeaders sets field value
func (o *EndpointHeadersIn) SetHeaders(v map[string]string) {
	o.Headers = v
}

func (o EndpointHeadersIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["headers"] = o.Headers
	}
	return json.Marshal(toSerialize)
}

type NullableEndpointHeadersIn struct {
	value *EndpointHeadersIn
	isSet bool
}

func (v NullableEndpointHeadersIn) Get() *EndpointHeadersIn {
	return v.value
}

func (v *NullableEndpointHeadersIn) Set(val *EndpointHeadersIn) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointHeadersIn) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointHeadersIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointHeadersIn(val *EndpointHeadersIn) *NullableEndpointHeadersIn {
	return &NullableEndpointHeadersIn{value: val, isSet: true}
}

func (v NullableEndpointHeadersIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointHeadersIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


