/*
 * Svix
 *
 * The Svix server API documentation
 *
 * API version: 1.4
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EndpointIn struct for EndpointIn
type EndpointIn struct {
	Url string `json:"url"`
	Version int32 `json:"version"`
	Description *string `json:"description,omitempty"`
	FilterTypes *[]string `json:"filterTypes,omitempty"`
}

// NewEndpointIn instantiates a new EndpointIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointIn(url string, version int32, ) *EndpointIn {
	this := EndpointIn{}
	this.Url = url
	this.Version = version
	var description string = ""
	this.Description = &description
	return &this
}

// NewEndpointInWithDefaults instantiates a new EndpointIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointInWithDefaults() *EndpointIn {
	this := EndpointIn{}
	var description string = ""
	this.Description = &description
	return &this
}

// GetUrl returns the Url field value
func (o *EndpointIn) GetUrl() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *EndpointIn) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *EndpointIn) SetUrl(v string) {
	o.Url = v
}

// GetVersion returns the Version field value
func (o *EndpointIn) GetVersion() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *EndpointIn) GetVersionOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *EndpointIn) SetVersion(v int32) {
	o.Version = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EndpointIn) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointIn) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EndpointIn) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EndpointIn) SetDescription(v string) {
	o.Description = &v
}

// GetFilterTypes returns the FilterTypes field value if set, zero value otherwise.
func (o *EndpointIn) GetFilterTypes() []string {
	if o == nil || o.FilterTypes == nil {
		var ret []string
		return ret
	}
	return *o.FilterTypes
}

// GetFilterTypesOk returns a tuple with the FilterTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointIn) GetFilterTypesOk() (*[]string, bool) {
	if o == nil || o.FilterTypes == nil {
		return nil, false
	}
	return o.FilterTypes, true
}

// HasFilterTypes returns a boolean if a field has been set.
func (o *EndpointIn) HasFilterTypes() bool {
	if o != nil && o.FilterTypes != nil {
		return true
	}

	return false
}

// SetFilterTypes gets a reference to the given []string and assigns it to the FilterTypes field.
func (o *EndpointIn) SetFilterTypes(v []string) {
	o.FilterTypes = &v
}

func (o EndpointIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["version"] = o.Version
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.FilterTypes != nil {
		toSerialize["filterTypes"] = o.FilterTypes
	}
	return json.Marshal(toSerialize)
}

type NullableEndpointIn struct {
	value *EndpointIn
	isSet bool
}

func (v NullableEndpointIn) Get() *EndpointIn {
	return v.value
}

func (v *NullableEndpointIn) Set(val *EndpointIn) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointIn) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointIn(val *EndpointIn) *NullableEndpointIn {
	return &NullableEndpointIn{value: val, isSet: true}
}

func (v NullableEndpointIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


