/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EventIn struct for EventIn
type EventIn struct {
	Payload string `json:"payload"`
}

// NewEventIn instantiates a new EventIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventIn(payload string) *EventIn {
	this := EventIn{}
	this.Payload = payload
	return &this
}

// NewEventInWithDefaults instantiates a new EventIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventInWithDefaults() *EventIn {
	this := EventIn{}
	return &this
}

// GetPayload returns the Payload field value
func (o *EventIn) GetPayload() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *EventIn) GetPayloadOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Payload, true
}

// SetPayload sets field value
func (o *EventIn) SetPayload(v string) {
	o.Payload = v
}

func (o EventIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["payload"] = o.Payload
	}
	return json.Marshal(toSerialize)
}

type NullableEventIn struct {
	value *EventIn
	isSet bool
}

func (v NullableEventIn) Get() *EventIn {
	return v.value
}

func (v *NullableEventIn) Set(val *EventIn) {
	v.value = val
	v.isSet = true
}

func (v NullableEventIn) IsSet() bool {
	return v.isSet
}

func (v *NullableEventIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventIn(val *EventIn) *NullableEventIn {
	return &NullableEventIn{value: val, isSet: true}
}

func (v NullableEventIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


