/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// HubspotOauthConfigIn struct for HubspotOauthConfigIn
type HubspotOauthConfigIn struct {
	RefreshToken string `json:"refresh_token"`
}

// NewHubspotOauthConfigIn instantiates a new HubspotOauthConfigIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHubspotOauthConfigIn(refreshToken string) *HubspotOauthConfigIn {
	this := HubspotOauthConfigIn{}
	this.RefreshToken = refreshToken
	return &this
}

// NewHubspotOauthConfigInWithDefaults instantiates a new HubspotOauthConfigIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHubspotOauthConfigInWithDefaults() *HubspotOauthConfigIn {
	this := HubspotOauthConfigIn{}
	return &this
}

// GetRefreshToken returns the RefreshToken field value
func (o *HubspotOauthConfigIn) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *HubspotOauthConfigIn) GetRefreshTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *HubspotOauthConfigIn) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o HubspotOauthConfigIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return json.Marshal(toSerialize)
}

type NullableHubspotOauthConfigIn struct {
	value *HubspotOauthConfigIn
	isSet bool
}

func (v NullableHubspotOauthConfigIn) Get() *HubspotOauthConfigIn {
	return v.value
}

func (v *NullableHubspotOauthConfigIn) Set(val *HubspotOauthConfigIn) {
	v.value = val
	v.isSet = true
}

func (v NullableHubspotOauthConfigIn) IsSet() bool {
	return v.isSet
}

func (v *NullableHubspotOauthConfigIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHubspotOauthConfigIn(val *HubspotOauthConfigIn) *NullableHubspotOauthConfigIn {
	return &NullableHubspotOauthConfigIn{value: val, isSet: true}
}

func (v NullableHubspotOauthConfigIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHubspotOauthConfigIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


