[rust]
template_dir = "rust/templates"
extra_mounts = [["rust/.rustfmt.toml", "/app/.rustfmt.toml"]]
extra_shell_commands = ["rm rust/src/api/{environment,health}.rs"]
openapi = "lib-openapi.json"

[[rust.task]]
template = "rust/templates/api_resource.rs.jinja"
output_dir = "rust/src/api"
[[rust.task]]
template = "rust/templates/component_type.rs.jinja"
output_dir = "rust/src/models"


[javascript]
template_dir = "javascript/templates"
openapi = "lib-openapi.json"

[[javascript.task]]
template = "javascript/templates/api_resource.ts.jinja"
output_dir = "javascript/src/api"
[[javascript.task]]
template = "javascript/templates/component_type_summary.ts.jinja"
output_dir = "javascript/src/models"
[[javascript.task]]
template = "javascript/templates/component_type.ts.jinja"
output_dir = "javascript/src/models"


[cli]
template_dir = "svix-cli/templates"
extra_mounts = [["svix-cli/.rustfmt.toml", "/app/.rustfmt.toml"]]
extra_shell_commands = [
    "cargo fix --manifest-path svix-cli/Cargo.toml --allow-dirty",
    "cargo fmt --manifest-path svix-cli/Cargo.toml",
    "rm svix-cli/src/cmds/api/{background_task,environment,health,operational_webhook_endpoint,statistics}.rs",
]
openapi = "lib-openapi.json"

[[cli.task]]
template = "svix-cli/templates/api_resource.rs.jinja"
output_dir = "svix-cli/src/cmds/api"


[python]
template_dir = "python/templates"
openapi = "lib-openapi.json"
extra_shell_commands = ["rm python/svix/api/{environment,health}.py"]

[[python.task]]
template = "python/templates/api_resource.py.jinja"
output_dir = "python/svix/api"
[[python.task]]
template = "python/templates/component_type_summary.py.jinja"
output_dir = "python/svix/models"
[[python.task]]
template = "python/templates/component_type.py.jinja"
output_dir = "python/svix/models"
