[graph]
targets = [
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
# there are multiple projects in here
unused-ignored-advisory = "allow"
ignore = [
    # TODO: Update dependencies that use rsa crate
    "RUSTSEC-2023-0071",
    # TODO: Wait for dependencies to upgrade off of proc-macro-error
    "RUSTSEC-2024-0370",
    # TODO: Wait for dependencies to upgrade off of paste
    "RUSTSEC-2024-0436",
    # rustls-pemfile is unmaintained, but we only use it for parsing system
    # certificates. This is not a serious attack vector for our use case.
    # TODO: Upgrade rustls-native-certs to 0.8.x to get rid of this.
    "RUSTSEC-2025-0134",
    # bincode (depended on by deno) is unmaintained
    "RUSTSEC-2025-0141",
    # can't upgrade to hickory 0.26 until https://github.com/seanmonstar/reqwest/pull/3014 is landed
    # on reqwest and all of our deps are updated to the new reqwest version
    "RUSTSEC-2026-0118",
    "RUSTSEC-2026-0119",
]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0", # MIT No Attribution
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Zlib",
]
unused-allowed-license = "allow"
unused-license-exception = "allow"
confidence-threshold = 0.8
exceptions = [
    { allow = ["EPL-2.0"], name = "colored_json", version = "*" }
]

# TODO: Include internal crates
[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
allow = []
deny = [
    # Versions containing the binary blob
    # See: https://github.com/serde-rs/serde/issues/2538
    { name = "serde_derive", version = ">1.0.171, <1.0.184"},
    { name = "axum", version = "<0.7" },
]
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/svix/hyper.git",
    "https://github.com/svix/omniqueue-rs.git",
    "https://github.com/svix/validator.git",
]
# there are several projects in here, so it's okay if we don't use them all
unused-allowed-source = "allow"
