version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticmq: # Drop-in SQS replacement
    image: softwaremill/elasticmq:1.3.14
    ports:
      - "9324:9324"
      - "9325:9325"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gcp-pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    ports:
      - "8085:8085"
    command: [
      "gcloud", "beta", "emulators", "pubsub", "start",
      "--project", "local-project",
      "--host-port", "0.0.0.0:8085"
    ]

  kinesis:
    # They don't seem to tag releases... might need to find a different image or build one of our own using the npm
    # package.
    image: instructure/kinesalite:latest
    ports:
      - "4567:4567"
