/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Svix.Client.FileParameter;
using OpenAPIDateConverter = Svix.Client.OpenAPIDateConverter;

namespace Svix.Model
{
    /// <summary>
    /// AggregatedEventTypes
    /// </summary>
    [DataContract(Name = "AggregatedEventTypes")]
    public partial class AggregatedEventTypes : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatedEventTypes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AggregatedEventTypes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatedEventTypes" /> class.
        /// </summary>
        /// <param name="appId">The app&#39;s ID (required).</param>
        /// <param name="explicitlySubscribedEventTypes">explicitlySubscribedEventTypes (required).</param>
        /// <param name="hasCatchAllEndpoint">hasCatchAllEndpoint (required).</param>
        public AggregatedEventTypes(string appId = default(string), List<string> explicitlySubscribedEventTypes = default(List<string>), bool hasCatchAllEndpoint = default(bool))
        {
            // to ensure "appId" is required (not null)
            if (appId == null)
            {
                throw new ArgumentNullException("appId is a required property for AggregatedEventTypes and cannot be null");
            }
            this.AppId = appId;
            // to ensure "explicitlySubscribedEventTypes" is required (not null)
            if (explicitlySubscribedEventTypes == null)
            {
                throw new ArgumentNullException("explicitlySubscribedEventTypes is a required property for AggregatedEventTypes and cannot be null");
            }
            this.ExplicitlySubscribedEventTypes = explicitlySubscribedEventTypes;
            this.HasCatchAllEndpoint = hasCatchAllEndpoint;
        }

        /// <summary>
        /// The app&#39;s ID
        /// </summary>
        /// <value>The app&#39;s ID</value>
        /*
        <example>app_1srOrx2ZWZBpBUvZwXKQmoEYga2</example>
        */
        [DataMember(Name = "appId", IsRequired = true, EmitDefaultValue = true)]
        public string AppId { get; set; }

        /// <summary>
        /// Gets or Sets ExplicitlySubscribedEventTypes
        /// </summary>
        [DataMember(Name = "explicitlySubscribedEventTypes", IsRequired = true, EmitDefaultValue = true)]
        public List<string> ExplicitlySubscribedEventTypes { get; set; }

        /// <summary>
        /// Gets or Sets HasCatchAllEndpoint
        /// </summary>
        [DataMember(Name = "hasCatchAllEndpoint", IsRequired = true, EmitDefaultValue = true)]
        public bool HasCatchAllEndpoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AggregatedEventTypes {\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  ExplicitlySubscribedEventTypes: ").Append(ExplicitlySubscribedEventTypes).Append("\n");
            sb.Append("  HasCatchAllEndpoint: ").Append(HasCatchAllEndpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
