/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Svix.Client.FileParameter;
using OpenAPIDateConverter = Svix.Client.OpenAPIDateConverter;

namespace Svix.Model
{
    /// <summary>
    /// EndpointOauthConfigIn
    /// </summary>
    [DataContract(Name = "EndpointOauthConfigIn")]
    public partial class EndpointOauthConfigIn : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets AuthMethod
        /// </summary>
        [DataMember(Name = "authMethod", IsRequired = true, EmitDefaultValue = true)]
        public Oauth2AuthMethodInOut AuthMethod { get; set; }

        /// <summary>
        /// Gets or Sets GrantType
        /// </summary>
        [DataMember(Name = "grantType", IsRequired = true, EmitDefaultValue = true)]
        public Oauth2GrantTypeInOut GrantType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EndpointOauthConfigIn" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EndpointOauthConfigIn() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EndpointOauthConfigIn" /> class.
        /// </summary>
        /// <param name="authMethod">authMethod (required).</param>
        /// <param name="clientId">The client ID. Required for all authentication types. (required).</param>
        /// <param name="clientSecret">Optional client secret. This is only used for &#x60;clientSecretBasic&#x60; and &#x60;clientSecretPost&#x60;.  For &#x60;clientSecretBasic&#x60;, the secret will be appended to the &#x60;Authorization&#x60; header. For &#x60;clientSecretPost&#x60;, this will be added to the body in a &#x60;client_secret&#x60; parameter..</param>
        /// <param name="extraParams">Extra parameters added to the request body as key-value pairs..</param>
        /// <param name="grantType">grantType (required).</param>
        /// <param name="jwtParams">jwtParams.</param>
        /// <param name="refreshToken">For &#x60;refreshToken&#x60; grant type..</param>
        /// <param name="scopes">Optional OAuth scopes added to the request body..</param>
        /// <param name="tokenUrl">The URL of the authorization server. (required).</param>
        public EndpointOauthConfigIn(Oauth2AuthMethodInOut authMethod = default(Oauth2AuthMethodInOut), string clientId = default(string), string clientSecret = default(string), Dictionary<string, string> extraParams = default(Dictionary<string, string>), Oauth2GrantTypeInOut grantType = default(Oauth2GrantTypeInOut), ClientSecretJwtParamsIn jwtParams = default(ClientSecretJwtParamsIn), string refreshToken = default(string), List<string> scopes = default(List<string>), string tokenUrl = default(string))
        {
            this.AuthMethod = authMethod;
            // to ensure "clientId" is required (not null)
            if (clientId == null)
            {
                throw new ArgumentNullException("clientId is a required property for EndpointOauthConfigIn and cannot be null");
            }
            this.ClientId = clientId;
            this.GrantType = grantType;
            // to ensure "tokenUrl" is required (not null)
            if (tokenUrl == null)
            {
                throw new ArgumentNullException("tokenUrl is a required property for EndpointOauthConfigIn and cannot be null");
            }
            this.TokenUrl = tokenUrl;
            this.ClientSecret = clientSecret;
            this.ExtraParams = extraParams;
            this.JwtParams = jwtParams;
            this.RefreshToken = refreshToken;
            this.Scopes = scopes;
        }

        /// <summary>
        /// The client ID. Required for all authentication types.
        /// </summary>
        /// <value>The client ID. Required for all authentication types.</value>
        [DataMember(Name = "clientId", IsRequired = true, EmitDefaultValue = true)]
        public string ClientId { get; set; }

        /// <summary>
        /// Optional client secret. This is only used for &#x60;clientSecretBasic&#x60; and &#x60;clientSecretPost&#x60;.  For &#x60;clientSecretBasic&#x60;, the secret will be appended to the &#x60;Authorization&#x60; header. For &#x60;clientSecretPost&#x60;, this will be added to the body in a &#x60;client_secret&#x60; parameter.
        /// </summary>
        /// <value>Optional client secret. This is only used for &#x60;clientSecretBasic&#x60; and &#x60;clientSecretPost&#x60;.  For &#x60;clientSecretBasic&#x60;, the secret will be appended to the &#x60;Authorization&#x60; header. For &#x60;clientSecretPost&#x60;, this will be added to the body in a &#x60;client_secret&#x60; parameter.</value>
        [DataMember(Name = "clientSecret", EmitDefaultValue = true)]
        public string ClientSecret { get; set; }

        /// <summary>
        /// Extra parameters added to the request body as key-value pairs.
        /// </summary>
        /// <value>Extra parameters added to the request body as key-value pairs.</value>
        [DataMember(Name = "extraParams", EmitDefaultValue = true)]
        public Dictionary<string, string> ExtraParams { get; set; }

        /// <summary>
        /// Gets or Sets JwtParams
        /// </summary>
        [DataMember(Name = "jwtParams", EmitDefaultValue = false)]
        public ClientSecretJwtParamsIn JwtParams { get; set; }

        /// <summary>
        /// For &#x60;refreshToken&#x60; grant type.
        /// </summary>
        /// <value>For &#x60;refreshToken&#x60; grant type.</value>
        [DataMember(Name = "refreshToken", EmitDefaultValue = true)]
        public string RefreshToken { get; set; }

        /// <summary>
        /// Optional OAuth scopes added to the request body.
        /// </summary>
        /// <value>Optional OAuth scopes added to the request body.</value>
        [DataMember(Name = "scopes", EmitDefaultValue = true)]
        public List<string> Scopes { get; set; }

        /// <summary>
        /// The URL of the authorization server.
        /// </summary>
        /// <value>The URL of the authorization server.</value>
        [DataMember(Name = "tokenUrl", IsRequired = true, EmitDefaultValue = true)]
        public string TokenUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EndpointOauthConfigIn {\n");
            sb.Append("  AuthMethod: ").Append(AuthMethod).Append("\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  ClientSecret: ").Append(ClientSecret).Append("\n");
            sb.Append("  ExtraParams: ").Append(ExtraParams).Append("\n");
            sb.Append("  GrantType: ").Append(GrantType).Append("\n");
            sb.Append("  JwtParams: ").Append(JwtParams).Append("\n");
            sb.Append("  RefreshToken: ").Append(RefreshToken).Append("\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  TokenUrl: ").Append(TokenUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
