apiVersion: v1
kind: Service
metadata:
  name: {{ include "svix.fullname" . }}-{{ .Values.pgbouncer.name }}
  labels:
    {{- include "svix.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
spec:
  type: {{ .Values.pgbouncer.service.type }}
  ports:
    - port: {{ .Values.pgbouncer.service.port }}
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
  selector:
    {{- include "svix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer 