apiVersion: v1
kind: Service
metadata:
  name: {{ include "svix.fullname" . }}-{{ .Values.postgres.name }}
  labels:
    {{- include "svix.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "svix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
