/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
        
                #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
                pub struct CreateMessageTokenIn {
                        /// How long the token will be valid for, in seconds.
                        #[serde(rename = "expiry", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
                        pub expiry: Option<Option<i32>>,
                        /// The name of the token.
                        #[serde(rename = "name")]
                        pub name: String,
                    }

                    impl CreateMessageTokenIn {
                    pub fn new(name: String) -> CreateMessageTokenIn {
                CreateMessageTokenIn {
                    expiry: None,
                    name,
                    }
                    }
                    }

