/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
        
                #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
                pub struct OAuthPayloadIn {
                        #[serde(rename = "code")]
                        pub code: String,
                        #[serde(rename = "redirectUri")]
                        pub redirect_uri: String,
                    }

                    impl OAuthPayloadIn {
                    pub fn new(code: String, redirect_uri: String) -> OAuthPayloadIn {
                OAuthPayloadIn {
                    code,
                    redirect_uri,
                    }
                    }
                    }

