/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
        
                /// 
                #[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
                pub enum Oauth2GrantTypeIn {
                        #[serde(rename = "clientCredentials")]
                        ClientCredentials,
                                            #[serde(rename = "refreshToken")]
                        RefreshToken,
                    
                }

                impl std::fmt::Display for Oauth2GrantTypeIn {
                fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                match self {
                        Self::ClientCredentials => write!(f, "clientCredentials"),
                        Self::RefreshToken => write!(f, "refreshToken"),
                }
                }
                }

            impl Default for Oauth2GrantTypeIn {
            fn default() -> Oauth2GrantTypeIn {
                Self::ClientCredentials
            }
            }

