/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
        
                #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
                pub struct StreamOut {
                        #[serde(rename = "createdAt")]
                        pub created_at: String,
                        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
                        pub description: Option<String>,
                        #[serde(rename = "id")]
                        pub id: String,
                        #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
                        pub uid: Option<String>,
                        #[serde(rename = "updatedAt")]
                        pub updated_at: String,
                    }

                    impl StreamOut {
                    pub fn new(created_at: String, id: String, updated_at: String) -> StreamOut {
                StreamOut {
                    created_at,
                    description: None,
                    id,
                    uid: None,
                    updated_at,
                    }
                    }
                    }

