/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
        
                #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
                pub struct StreamPatch {
                        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
                        pub description: Option<String>,
                        #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
                        pub uid: Option<String>,
                    }

                    impl StreamPatch {
                    pub fn new() -> StreamPatch {
                StreamPatch {
                    description: None,
                    uid: None,
                    }
                    }
                    }

