/*
 * Svix API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use crate::models;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
        
                #[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
                pub struct TemplateIn {
                        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
                        pub description: Option<String>,
                        #[serde(rename = "featureFlag", skip_serializing_if = "Option::is_none")]
                        pub feature_flag: Option<String>,
                        #[serde(rename = "filterTypes", skip_serializing_if = "Option::is_none")]
                        pub filter_types: Option<Vec<String>>,
                        #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
                        pub instructions: Option<String>,
                        #[serde(rename = "instructionsLink", skip_serializing_if = "Option::is_none")]
                        pub instructions_link: Option<String>,
                        #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
                        pub kind: Option<models::TransformationTemplateKind>,
                        #[serde(rename = "logo")]
                        pub logo: String,
                        #[serde(rename = "name")]
                        pub name: String,
                        #[serde(rename = "transformation")]
                        pub transformation: String,
                    }

                    impl TemplateIn {
                    pub fn new(logo: String, name: String, transformation: String) -> TemplateIn {
                TemplateIn {
                    description: None,
                    feature_flag: None,
                    filter_types: None,
                    instructions: None,
                    instructions_link: None,
                    kind: None,
                    logo,
                    name,
                    transformation,
                    }
                    }
                    }

