<?php
/**
 * EventTypeApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Svix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Svix API
 *
 * Welcome to the Svix API documentation!  Useful links: [Homepage](https://www.svix.com) | [Support email](mailto:support+docs@svix.com) | [Blog](https://www.svix.com/blog/) | [Slack Community](https://www.svix.com/slack/)  # Introduction  This is the reference documentation and schemas for the [Svix webhook service](https://www.svix.com) API. For tutorials and other documentation please refer to [the documentation](https://docs.svix.com).  ## Main concepts  In Svix you have four important entities you will be interacting with:  - `messages`: these are the webhooks being sent. They can have contents and a few other properties. - `application`: this is where `messages` are sent to. Usually you want to create one application for each of your users. - `endpoint`: endpoints are the URLs messages will be sent to. Each application can have multiple `endpoints` and each message sent to that application will be sent to all of them (unless they are not subscribed to the sent event type). - `event-type`: event types are identifiers denoting the type of the message being sent. Event types are primarily used to decide which events are sent to which endpoint.   ## Authentication  Get your authentication token (`AUTH_TOKEN`) from the [Svix dashboard](https://dashboard.svix.com) and use it as part of the `Authorization` header as such: `Authorization: Bearer ${AUTH_TOKEN}`.  <SecurityDefinitions />   ## Code samples  The code samples assume you already have the respective libraries installed and you know how to use them. For the latest information on how to do that, please refer to [the documentation](https://docs.svix.com/).   ## Cross-Origin Resource Sharing  This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.
 *
 * The version of the OpenAPI document: 1.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Svix\Svix\Internal\API;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Svix\ApiException;
use Svix\Configuration;
use Svix\HeaderSelector;
use Svix\ObjectSerializer;

/**
 * EventTypeApi Class Doc Comment
 *
 * @category Class
 * @package  Svix
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventTypeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createEventTypeApiV1EventTypePost
     *
     * Create Event Type
     *
     * @param  \Svix\Svix\Models\EventTypeIn $event_type_in event_type_in (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Svix\Svix\Models\EventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError
     */
    public function createEventTypeApiV1EventTypePost($event_type_in)
    {
        list($response) = $this->createEventTypeApiV1EventTypePostWithHttpInfo($event_type_in);
        return $response;
    }

    /**
     * Operation createEventTypeApiV1EventTypePostWithHttpInfo
     *
     * Create Event Type
     *
     * @param  \Svix\Svix\Models\EventTypeIn $event_type_in (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Svix\Svix\Models\EventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createEventTypeApiV1EventTypePostWithHttpInfo($event_type_in)
    {
        $request = $this->createEventTypeApiV1EventTypePostRequest($event_type_in);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Svix\Svix\Models\EventTypeOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\EventTypeOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\Svix\Svix\Models\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Svix\Svix\Models\EventTypeOut';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\EventTypeOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createEventTypeApiV1EventTypePostAsync
     *
     * Create Event Type
     *
     * @param  \Svix\Svix\Models\EventTypeIn $event_type_in (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createEventTypeApiV1EventTypePostAsync($event_type_in)
    {
        return $this->createEventTypeApiV1EventTypePostAsyncWithHttpInfo($event_type_in)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createEventTypeApiV1EventTypePostAsyncWithHttpInfo
     *
     * Create Event Type
     *
     * @param  \Svix\Svix\Models\EventTypeIn $event_type_in (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createEventTypeApiV1EventTypePostAsyncWithHttpInfo($event_type_in)
    {
        $returnType = '\Svix\Svix\Models\EventTypeOut';
        $request = $this->createEventTypeApiV1EventTypePostRequest($event_type_in);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createEventTypeApiV1EventTypePost'
     *
     * @param  \Svix\Svix\Models\EventTypeIn $event_type_in (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createEventTypeApiV1EventTypePostRequest($event_type_in)
    {
        // verify the required parameter 'event_type_in' is set
        if ($event_type_in === null || (is_array($event_type_in) && count($event_type_in) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_in when calling createEventTypeApiV1EventTypePost'
            );
        }

        $resourcePath = '/api/v1/event-type/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($event_type_in)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($event_type_in));
            } else {
                $httpBody = $event_type_in;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteEventTypeApiV1EventTypeEventTypeNameDelete
     *
     * Delete Event Type
     *
     * @param  string $event_type_name event_type_name (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteEventTypeApiV1EventTypeEventTypeNameDelete($event_type_name)
    {
        $this->deleteEventTypeApiV1EventTypeEventTypeNameDeleteWithHttpInfo($event_type_name);
    }

    /**
     * Operation deleteEventTypeApiV1EventTypeEventTypeNameDeleteWithHttpInfo
     *
     * Delete Event Type
     *
     * @param  string $event_type_name (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteEventTypeApiV1EventTypeEventTypeNameDeleteWithHttpInfo($event_type_name)
    {
        $request = $this->deleteEventTypeApiV1EventTypeEventTypeNameDeleteRequest($event_type_name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteEventTypeApiV1EventTypeEventTypeNameDeleteAsync
     *
     * Delete Event Type
     *
     * @param  string $event_type_name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteEventTypeApiV1EventTypeEventTypeNameDeleteAsync($event_type_name)
    {
        return $this->deleteEventTypeApiV1EventTypeEventTypeNameDeleteAsyncWithHttpInfo($event_type_name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteEventTypeApiV1EventTypeEventTypeNameDeleteAsyncWithHttpInfo
     *
     * Delete Event Type
     *
     * @param  string $event_type_name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteEventTypeApiV1EventTypeEventTypeNameDeleteAsyncWithHttpInfo($event_type_name)
    {
        $returnType = '';
        $request = $this->deleteEventTypeApiV1EventTypeEventTypeNameDeleteRequest($event_type_name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteEventTypeApiV1EventTypeEventTypeNameDelete'
     *
     * @param  string $event_type_name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteEventTypeApiV1EventTypeEventTypeNameDeleteRequest($event_type_name)
    {
        // verify the required parameter 'event_type_name' is set
        if ($event_type_name === null || (is_array($event_type_name) && count($event_type_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_name when calling deleteEventTypeApiV1EventTypeEventTypeNameDelete'
            );
        }
        if (strlen($event_type_name) > 256) {
            throw new \InvalidArgumentException('invalid length for "$event_type_name" when calling EventTypeApi.deleteEventTypeApiV1EventTypeEventTypeNameDelete, must be smaller than or equal to 256.');
        }
        if (!preg_match("/^[a-zA-Z0-9\\-_.]+$/", $event_type_name)) {
            throw new \InvalidArgumentException("invalid value for \"event_type_name\" when calling EventTypeApi.deleteEventTypeApiV1EventTypeEventTypeNameDelete, must conform to the pattern /^[a-zA-Z0-9\\-_.]+$/.");
        }


        $resourcePath = '/api/v1/event-type/{event_type_name}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($event_type_name !== null) {
            $resourcePath = str_replace(
                '{' . 'event_type_name' . '}',
                ObjectSerializer::toPathValue($event_type_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEventTypeApiV1EventTypeEventTypeNameGet
     *
     * Get Event Type
     *
     * @param  string $event_type_name event_type_name (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Svix\Svix\Models\EventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError
     */
    public function getEventTypeApiV1EventTypeEventTypeNameGet($event_type_name)
    {
        list($response) = $this->getEventTypeApiV1EventTypeEventTypeNameGetWithHttpInfo($event_type_name);
        return $response;
    }

    /**
     * Operation getEventTypeApiV1EventTypeEventTypeNameGetWithHttpInfo
     *
     * Get Event Type
     *
     * @param  string $event_type_name (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Svix\Svix\Models\EventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEventTypeApiV1EventTypeEventTypeNameGetWithHttpInfo($event_type_name)
    {
        $request = $this->getEventTypeApiV1EventTypeEventTypeNameGetRequest($event_type_name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Svix\Svix\Models\EventTypeOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\EventTypeOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\Svix\Svix\Models\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Svix\Svix\Models\EventTypeOut';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\EventTypeOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEventTypeApiV1EventTypeEventTypeNameGetAsync
     *
     * Get Event Type
     *
     * @param  string $event_type_name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventTypeApiV1EventTypeEventTypeNameGetAsync($event_type_name)
    {
        return $this->getEventTypeApiV1EventTypeEventTypeNameGetAsyncWithHttpInfo($event_type_name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEventTypeApiV1EventTypeEventTypeNameGetAsyncWithHttpInfo
     *
     * Get Event Type
     *
     * @param  string $event_type_name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventTypeApiV1EventTypeEventTypeNameGetAsyncWithHttpInfo($event_type_name)
    {
        $returnType = '\Svix\Svix\Models\EventTypeOut';
        $request = $this->getEventTypeApiV1EventTypeEventTypeNameGetRequest($event_type_name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEventTypeApiV1EventTypeEventTypeNameGet'
     *
     * @param  string $event_type_name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEventTypeApiV1EventTypeEventTypeNameGetRequest($event_type_name)
    {
        // verify the required parameter 'event_type_name' is set
        if ($event_type_name === null || (is_array($event_type_name) && count($event_type_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_name when calling getEventTypeApiV1EventTypeEventTypeNameGet'
            );
        }
        if (strlen($event_type_name) > 256) {
            throw new \InvalidArgumentException('invalid length for "$event_type_name" when calling EventTypeApi.getEventTypeApiV1EventTypeEventTypeNameGet, must be smaller than or equal to 256.');
        }
        if (!preg_match("/^[a-zA-Z0-9\\-_.]+$/", $event_type_name)) {
            throw new \InvalidArgumentException("invalid value for \"event_type_name\" when calling EventTypeApi.getEventTypeApiV1EventTypeEventTypeNameGet, must conform to the pattern /^[a-zA-Z0-9\\-_.]+$/.");
        }


        $resourcePath = '/api/v1/event-type/{event_type_name}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($event_type_name !== null) {
            $resourcePath = str_replace(
                '{' . 'event_type_name' . '}',
                ObjectSerializer::toPathValue($event_type_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listEventTypesApiV1EventTypeGet
     *
     * List Event Types
     *
     * @param  string $iterator iterator (optional)
     * @param  int $limit limit (optional, default to 50)
     * @param  bool $with_content with_content (optional, default to false)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Svix\Svix\Models\ListResponseEventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError
     */
    public function listEventTypesApiV1EventTypeGet($iterator = null, $limit = 50, $with_content = false)
    {
        list($response) = $this->listEventTypesApiV1EventTypeGetWithHttpInfo($iterator, $limit, $with_content);
        return $response;
    }

    /**
     * Operation listEventTypesApiV1EventTypeGetWithHttpInfo
     *
     * List Event Types
     *
     * @param  string $iterator (optional)
     * @param  int $limit (optional, default to 50)
     * @param  bool $with_content (optional, default to false)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Svix\Svix\Models\ListResponseEventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listEventTypesApiV1EventTypeGetWithHttpInfo($iterator = null, $limit = 50, $with_content = false)
    {
        $request = $this->listEventTypesApiV1EventTypeGetRequest($iterator, $limit, $with_content);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Svix\Svix\Models\ListResponseEventTypeOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\ListResponseEventTypeOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\Svix\Svix\Models\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Svix\Svix\Models\ListResponseEventTypeOut';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\ListResponseEventTypeOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listEventTypesApiV1EventTypeGetAsync
     *
     * List Event Types
     *
     * @param  string $iterator (optional)
     * @param  int $limit (optional, default to 50)
     * @param  bool $with_content (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEventTypesApiV1EventTypeGetAsync($iterator = null, $limit = 50, $with_content = false)
    {
        return $this->listEventTypesApiV1EventTypeGetAsyncWithHttpInfo($iterator, $limit, $with_content)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listEventTypesApiV1EventTypeGetAsyncWithHttpInfo
     *
     * List Event Types
     *
     * @param  string $iterator (optional)
     * @param  int $limit (optional, default to 50)
     * @param  bool $with_content (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listEventTypesApiV1EventTypeGetAsyncWithHttpInfo($iterator = null, $limit = 50, $with_content = false)
    {
        $returnType = '\Svix\Svix\Models\ListResponseEventTypeOut';
        $request = $this->listEventTypesApiV1EventTypeGetRequest($iterator, $limit, $with_content);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listEventTypesApiV1EventTypeGet'
     *
     * @param  string $iterator (optional)
     * @param  int $limit (optional, default to 50)
     * @param  bool $with_content (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listEventTypesApiV1EventTypeGetRequest($iterator = null, $limit = 50, $with_content = false)
    {

        $resourcePath = '/api/v1/event-type/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($iterator !== null) {
            if('form' === 'form' && is_array($iterator)) {
                foreach($iterator as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['iterator'] = $iterator;
            }
        }
        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($with_content !== null) {
            if('form' === 'form' && is_array($with_content)) {
                foreach($with_content as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['with_content'] = $with_content;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateEventTypeApiV1EventTypeEventTypeNamePut
     *
     * Update Event Type
     *
     * @param  string $event_type_name event_type_name (required)
     * @param  \Svix\Svix\Models\EventTypeUpdate $event_type_update event_type_update (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Svix\Svix\Models\EventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError
     */
    public function updateEventTypeApiV1EventTypeEventTypeNamePut($event_type_name, $event_type_update)
    {
        list($response) = $this->updateEventTypeApiV1EventTypeEventTypeNamePutWithHttpInfo($event_type_name, $event_type_update);
        return $response;
    }

    /**
     * Operation updateEventTypeApiV1EventTypeEventTypeNamePutWithHttpInfo
     *
     * Update Event Type
     *
     * @param  string $event_type_name (required)
     * @param  \Svix\Svix\Models\EventTypeUpdate $event_type_update (required)
     *
     * @throws \Svix\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Svix\Svix\Models\EventTypeOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HttpErrorOut|\Svix\Svix\Models\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateEventTypeApiV1EventTypeEventTypeNamePutWithHttpInfo($event_type_name, $event_type_update)
    {
        $request = $this->updateEventTypeApiV1EventTypeEventTypeNamePutRequest($event_type_name, $event_type_update);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Svix\Svix\Models\EventTypeOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\EventTypeOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Svix\Svix\Models\HttpErrorOut' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HttpErrorOut', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\Svix\Svix\Models\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Svix\Svix\Models\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Svix\Svix\Models\EventTypeOut';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\EventTypeOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HttpErrorOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Svix\Svix\Models\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateEventTypeApiV1EventTypeEventTypeNamePutAsync
     *
     * Update Event Type
     *
     * @param  string $event_type_name (required)
     * @param  \Svix\Svix\Models\EventTypeUpdate $event_type_update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateEventTypeApiV1EventTypeEventTypeNamePutAsync($event_type_name, $event_type_update)
    {
        return $this->updateEventTypeApiV1EventTypeEventTypeNamePutAsyncWithHttpInfo($event_type_name, $event_type_update)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateEventTypeApiV1EventTypeEventTypeNamePutAsyncWithHttpInfo
     *
     * Update Event Type
     *
     * @param  string $event_type_name (required)
     * @param  \Svix\Svix\Models\EventTypeUpdate $event_type_update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateEventTypeApiV1EventTypeEventTypeNamePutAsyncWithHttpInfo($event_type_name, $event_type_update)
    {
        $returnType = '\Svix\Svix\Models\EventTypeOut';
        $request = $this->updateEventTypeApiV1EventTypeEventTypeNamePutRequest($event_type_name, $event_type_update);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateEventTypeApiV1EventTypeEventTypeNamePut'
     *
     * @param  string $event_type_name (required)
     * @param  \Svix\Svix\Models\EventTypeUpdate $event_type_update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateEventTypeApiV1EventTypeEventTypeNamePutRequest($event_type_name, $event_type_update)
    {
        // verify the required parameter 'event_type_name' is set
        if ($event_type_name === null || (is_array($event_type_name) && count($event_type_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_name when calling updateEventTypeApiV1EventTypeEventTypeNamePut'
            );
        }
        if (strlen($event_type_name) > 256) {
            throw new \InvalidArgumentException('invalid length for "$event_type_name" when calling EventTypeApi.updateEventTypeApiV1EventTypeEventTypeNamePut, must be smaller than or equal to 256.');
        }
        if (!preg_match("/^[a-zA-Z0-9\\-_.]+$/", $event_type_name)) {
            throw new \InvalidArgumentException("invalid value for \"event_type_name\" when calling EventTypeApi.updateEventTypeApiV1EventTypeEventTypeNamePut, must conform to the pattern /^[a-zA-Z0-9\\-_.]+$/.");
        }

        // verify the required parameter 'event_type_update' is set
        if ($event_type_update === null || (is_array($event_type_update) && count($event_type_update) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_update when calling updateEventTypeApiV1EventTypeEventTypeNamePut'
            );
        }

        $resourcePath = '/api/v1/event-type/{event_type_name}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($event_type_name !== null) {
            $resourcePath = str_replace(
                '{' . 'event_type_name' . '}',
                ObjectSerializer::toPathValue($event_type_name),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($event_type_update)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($event_type_update));
            } else {
                $httpBody = $event_type_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
