name: CLI Lint

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: svix-cli

jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: rustfmt
        run: cargo fmt -- --check

  cargo-sort:
    name: 'Run cargo-sort'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        name: Checkout

      - name: Install cargo sort
        uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: cargo-sort

      - name: Run cargo sort
        run: cargo sort --workspace --check --check-format

  hadolint:
    name: Run Hadolint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: svix-cli/Dockerfile

  test-versions:
    name: CLI Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # keep this in sync with svix-cli/Cargo.toml MSRV
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: "svix-cli -> target"
          # only save the cache on the main branch
          # cf https://github.com/Swatinem/rust-cache/issues/95
          save-if: ${{ github.ref == 'refs/heads/main' }}
          # include relevant information in the cache name
          prefix-key: "cli-${{ matrix.rust }}"

      - uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: nextest

      - name: Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo nextest run
