name: CLI Lint

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: svix-cli

jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: rustfmt
        run: cargo fmt -- --check

  cargo-sort:
    name: 'Run cargo-sort'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        name: Checkout

      - name: Install cargo sort
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: cargo-sort

      - name: Run cargo sort
        run: cargo sort --workspace --check --check-format

  test-versions:
    name: CLI Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # keep this in sync with svix-cli/Cargo.toml MSRV
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v6

      - name: Regen openapi libs
        run: ../regen_openapi.py

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "svix-cli -> target"
          # only save the cache on the main branch
          # cf https://github.com/Swatinem/rust-cache/issues/95
          save-if: ${{ github.ref == 'refs/heads/main' }}
          # include relevant information in the cache name
          prefix-key: "cli-${{ matrix.rust }}"

      - uses: taiki-e/install-action@nextest

      - name: Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo nextest run
