name: PHP CI

on:
  workflow_call:
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.3', '8.4', '8.5']
        dependencies: ['highest', 'lowest']
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Install php
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Install Composer dependencies ${{ matrix.dependencies }}
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist --prefer-stable

      - name: Run unit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
