name: Python Lint
on:
  workflow_call:
jobs:
  python-lint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        working-directory: python/
        run: uv sync

      - name: Run linting
        working-directory: python/
        run: uv run ./scripts/lint.sh

  python-test-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.14
      - name: Install deps
        working-directory: ./python
        run: uv sync
      - name: Build wheels
        run: uv build
        working-directory: ./python
      - name: Test install wheels
        run: |
          mkdir /tmp/test-install
          cd /tmp/test-install
          uv run --python '3.14' python3 -m venv venv
          venv/bin/pip install "${{ github.workspace }}"/python/dist/svix*.whl
          venv/bin/python -c 'import svix ; print(svix.__version__)'
