name: Ruby Lint and Tests

on:
  workflow_call:

jobs:
  ruby:
    name: Ruby Lint and Tests and Tests
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby-version: [3.2.10, 3.3.10, 3.4.9, 4.0.2]

    steps:
      - uses: actions/checkout@v7

      - name: Pull svix server image (and dependencies)
        run: docker compose pull
        working-directory: ./client-integration-tests

      - name: Setup Ruby
        uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        working-directory: ruby
        run: bundle install

      - name: Build
        working-directory: ruby
        run: bundle exec rake build

      - name: Test
        working-directory: ruby
        run: bundle exec rspec spec
