name: Ruby Lint and Tests

on:
  workflow_call:

jobs:
  ruby:
    name: Ruby Lint and Tests and Tests
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby-version: [3.2.10, 3.3.10, 3.4.9, 4.0.2]

    steps:
      - uses: actions/checkout@v7

      - name: Pull svix server image (and dependencies)
        run: docker compose pull
        working-directory: ./client-integration-tests

      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        working-directory: ruby
        run: bundle install

      - name: Build
        working-directory: ruby
        run: bundle exec rake build

      - name: Test
        working-directory: ruby
        run: bundle exec rspec spec
