name: Rust Lib Security

on:
  push:
    branches:
      - main
    paths:
      - 'rust/**/Cargo.toml'
      - 'rust/**/Cargo.lock'
      - '.github/workflows/rust-security.yml'
  pull_request:
    paths:
      - 'rust/**/Cargo.toml'
      - 'rust/**/Cargo.lock'
      - '.github/workflows/rust-security.yml'

jobs:
  security_audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          manifest-path: rust/Cargo.toml
