name: Server CI

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

defaults:
  run:
    working-directory: server

jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: rustfmt
        run: cargo fmt -- --check

  check-unused-deps:
    name: Check for unused dependencies
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: cargo-machete

      - run: cargo machete

  cargo-sort:
    name: 'Run cargo-sort'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        name: Checkout

      - name: Install cargo sort
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: cargo-sort

      - name: Run cargo sort
        run: cargo sort --workspace --check --check-format

  test-versions:
    name: Server CI
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # bump this when bumping the MSRV
        rust: ["1.88.0", stable, beta]
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "server -> target"
          # only save the cache on the main branch
          # cf https://github.com/Swatinem/rust-cache/issues/95
          save-if: ${{ github.ref == 'refs/heads/main' }}
          # include relevant information in the cache name
          prefix-key: "server-${{ matrix.rust }}"

      - uses: taiki-e/install-action@nextest

      - name: Build
        run: cargo test --all-features --no-run --locked

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Check for uncommitted OpenAPI changes
        run: ./generate-openapi.sh --check

      - name: Start dependencies
        run: docker compose -f "testing-docker-compose.yml" up -d

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run migrations
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          SVIX_REDIS_DSN: "redis://localhost:6379"
          SVIX_QUEUE_TYPE: "redis"
          SVIX_JWT_SECRET: "test value"
          SVIX_CACHE_TYPE: "memory"
        run: cargo run -- --wait-for 15 migrate

      - name: Run tests
        run: ./run-tests.sh

      - name: Stop dependencies
        run: docker compose -f "testing-docker-compose.yml" down
