name: Server docker image CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/Dockerfile'
      - '.github/workflows/server-docker-image.yml'
  workflow_call:

defaults:
  run:
    working-directory: server

jobs:
  test-image:
    name: Server docker image CI
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Build server image
        run: docker compose build

      - name: Run server with docker-compose
        run: docker compose up -d

      - name: Check server container is up and running
        run: curl --retry 5 --retry-all-errors http://localhost:8071/api/v1/health/

      - name: Display server container logs
        if: failure()
        run: docker compose logs backend

      - name: Terminate docker compose created containers
        if: always()
        run: docker compose down -v

  hadolint:
    name: Server docker image hadolint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: server/Dockerfile
