name: Webhook Bridge Release

on:
  push:
    branches:
      - onelson/bridge

jobs:
  docker:
    name: release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Derive Version Numbers
        # FIXME: don't have a release name when running on a branch push - hardcode to 0.0.0 for now
        run: |
          export REPO="${{ secrets.DOCKERHUB_USERNAME }}/svix-webhook-bridge"
          echo DOCKER_TAGS="$(echo "v0.0.0" | sed -E "s#v([0-9]+)\.([0-9]+)\.([0-9]+)#${REPO}:latest,${REPO}:v\1.\2.\3,${REPO}:v\1.\2,${REPO}:v\1#")" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./webhook-bridge
          file: ./webhook-bridge/Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          platforms: linux/amd64
